version: '3'

services:
    CoreDNS:
        image: coredns/coredns
        name: coredns
        args:
            - PHP_SOCKET=php:9000
        volumes: 
            - ./data/:/root/
        ports:
            - "53:53"
